name: Assembly
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
      symbols:
        description: Symbols

jobs:
  assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          llvm-objdump-18 -d --no-leading-addr --no-show-raw-insn ${{ inputs.symbols && format('--disassemble-symbols="{0}"', inputs.symbols) || '' }} "$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")" | llvm-cxxfilt-18 | sed -E '
            s/^[[:space:]]+//
            s/[[:space:]]+/ /g
            s/<(.+)>:$/\1/
          ' > assembly.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: assembly
          path: assembly.txt
