name: Assembly
on:
  workflow_dispatch:
    inputs:
      disassemble-symbols:
        description: Disassemble symbols
      start-address:
        description: Start address
      stop-address:
        description: Stop address
      no-leading-addresses:
        description: No leading addresses
        default: true
        type: boolean
      no-show-raw-instructions:
        description: No show raw instructions
        default: true
        type: boolean

jobs:
  assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          zstd -d "(curl -sSLOJ -w %{filename_effective} "${{ vars.URL }}")"
          llvm-objdump-18 -d ${{ inputs.no-leading-addresses && '--no-leading-addr' || '' }} ${{ inputs.no-show-raw-instructions && '--no-show-raw-insn' || '' }} ${{ inputs.disassemble-symbols  && format('--disassemble-symbols="{0}"', inputs.disassemble-symbols) || '' }} ${{ inputs.start-address && format('--start-address="{0}"', inputs.start-address) || '' }} ${{ inputs.stop-address && format('--stop-address="{0}"', inputs.stop-address) || '' }} *.so | llvm-cxxfilt-18 | sed -E '
            s/^\s+//
            s/\s+/ /g
            s/^([0-9a-fA-F]+ )?<(.+)>:$/\2/
          ' > assembly.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: assembly
          path: assembly.txt
