name: Assembly
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
      disassemble-symbols:
        description: Disassemble symbols
      start-address:
        description: Start address
      stop-address:
        description: Stop address

jobs:
  assembly:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          filename="$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")"
          llvm-objdump-18 -d --no-show-raw-insn ${{ inputs.disassemble-symbols  && format('--disassemble-symbols="{0}"', inputs.disassemble-symbols) || '' }} ${{ inputs.start-address && format('--start-address="{0}"', inputs.start-address) || '' }} {{ inputs.stop-address && format('--stop-address="{0}"', inputs.stop-address) || '' }} "$filename" | llvm-cxxfilt-18 | sed -E '
            s/^[ \t]+//
            s/[ \t]+/ /g
            s/^([0-9a-fA-F]+ )?<(.+)>:$/\2/
          ' > assembly.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: assembly
          path: assembly.txt
