name: Info
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
  
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |  
          zstd -qd "$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")"

          paste -d " " <(llvm-nm-18 -DjC *.so) <(llvm-nm-18 -DP *.so) | sed -E 's/^(\S+) \1/\1/' > names.txt
          llvm-strings-18 -t x *.so | sed -E 's/^ +//' > strings.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: info
          path: |
            names.txt
            strings.txt
