name: LLVM
on:
  workflow_dispatch:
    inputs:
      symbols:
        description: Symbols
      leading-addresses:
        description: Leading addresses
        type: boolean

jobs:
  llvm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run
        run: |
          llvm-nm-18 -D -f posix *.so > nm.txt

          if [[ -n "${{ inputs.symbols }}" ]]; then
            llvm-objdump-18 ${{ inputs.leading-addresses && '--no-show-raw-insn' || '--no-leading-addr --no-show-raw-insn' }} --disassemble-symbols="${{ inputs.symbols }}" *.so | llvm-cxxfilt-18 | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//; s/[[:space:]]+/ /g; s/^[[:xdigit:]]+ <([^>]+)>:$/\1/;' > objdump.txt
          fi

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: nm.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: objdump.txt
