name: Names
on: workflow_dispatch
  
jobs:
  names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run
        run: llvm-nm-18 -nDC *.so > names.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: names.txt
