name: Names
on:
  workflow_dispatch:
    inputs:
      format:
        description: Format
        options: [bsd, darwin, just-symbols, posix, sysv]
        type: choice
  
jobs:
  names:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run
        run: llvm-nm-18 -D -f "${{ inputs.format }}" --defined-only *.so > "${{ inputs.format }}.txt"

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: ${{ inputs.format }}.txt
