name: Radare2
on:
  workflow_dispatch:
    inputs:
      offset:
        description: Offset
        required: true
  
jobs:
  radare2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install and run

        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends radare2

          # 1. Dump the code right after af1004 in Update():
          echo "=== Inside Update() after af1004 ==="
          llvm-objdump-18 -d -C --start-address=0xaf1000 --stop-address=0xaf1030 *.so > e.txt

          # 2. Print the exact string FindElementByName was searching for at 0x4ba56b:
          echo "=== Child Element Name ==="
          r2 -q -c "ps @ 0x4ba56b" *.so > r2.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: archive
          path: "*.txt"
