name: Rizin
on: workflow_dispatch
  
jobs:
  rizin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run Decompiler
        run: docker run --entrypoint /bin/sh -e RZ_LOGLEVEL=1 -v "$PWD:/wd" rizin/rizin:latest -c "rizin -q -c 'af @ 0x8f18a0; af @ 0x8f01dc; pdg @ 0x8f01dc' /wd/*.so" > upload.c

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: upload.c
