name: Rizin
on: workflow_dispatch
  
jobs:
  rizin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run
        run: |
          docker run -v "$PWD:/pwd" rizin/rizin:latest sh -c 'rizin -q -c "aaa" /pwd/*.so'

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: rizin.txt
