name: Rizin
on: workflow_dispatch
  
jobs:
  rizin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run
        run: docker run -v "$PWD:/pwd" --entrypoint /bin/sh rizin/rizin:latest -c "export RZ_LOGLEVEL=0; export RZ_LOGSHOWSOURCES=1; rizin -q -z -c 'aa; pdg @ 0x8f01dc' /pwd/*.so" > upload.c

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: upload.c
