name: Symbols
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
  
jobs:
  symbols:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: llvm-nm-18 -D -f posix "$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")" > symbols.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: symbols
          path: symbols.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: symbols.txt
