name: Symbols
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
  
jobs:
  symbols:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          filename="$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")"

          llvm-nm-18 -DnC "$filename" > demangled.txt
          llvm-nm-18 -Dn "$filename" > mangled.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: symbols
          path: "*.txt"
