name: Symbols
on: workflow_dispatch
  
jobs:
  symbols:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: |
          filename="$(curl -sSLOJ -w %{filename_effective} "${{ vars.URL }}")"

          llvm-nm-18 -DC "$filename" > demangled.txt
          llvm-nm-18 -D "$filename" > mangled.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: demangled
          path: demangled.txt

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: mangled
          path: mangled.txt
