name: Test
on: workflow_dispatch
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run
        run: |
          unzip -q "$(curl -sSLOJ -w %{filename_effective} https://apkcombo.com/r2?u=https%3A%2F%2Fapks.39b7cb94d40914bac590886981b0ed6e.r2.cloudflarestorage.com%2Fcom.DVloper.Granny3%2F1.3%2F13.3432a06f98df34bc564aaa0af45fd36f95a9b575.apks%3Fresponse-content-disposition%3Dattachment%253B%2520filename%253D%2522Granny%25203_1.3_apkcombo.com.xapk%2522%26response-content-type%3Dapplication%252Fxapk-package-archive%26X-Amz-Algorithm%3DAWS4-HMAC-SHA256%26X-Amz-Date%3D20260907T143857Z%26X-Amz-SignedHeaders%3Dhost%26X-Amz-Expires%3D14400%26X-Amz-Credential%3D3cb727b4cd4780c410b780ac7caa4da3%252F20260907%252Fauto%252Fs3%252Faws4_request%26X-Amz-Signature%3Dbc3275fe678793b48f8fa379ff5c7c7d50a7fe607b5bb4d2a41f0063ce188070&fp=1e2f7b691176b5fcf7f9c5db2855b227&ip=203.78.120.224&package_name=com.DVloper.Granny3&lang=en)"
          unzip -q config.arm64_v8a.apk

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: libs
          files: lib/arm64-v8a/libil2cpp.so
