name: Test
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run
        run: |
          unzip -q "$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")"
          unzip -q -o com.DVloper.Granny3.apk
          unzip -q -o config.arm64_v8a.apk

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: test
          path: |
            lib/arm64-v8a/libil2cpp.so
            assets/bin/Data/Managed/Metadata/global-metadata.dat

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: test
          files: |
            lib/arm64-v8a/libil2cpp.so
            assets/bin/Data/Managed/Metadata/global-metadata.dat
