name: Test
on:
  workflow_dispatch:
    inputs:
      url:
        description: URL
        required: true
  
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run
        run: |
          unzip -q "$(curl -sSLOJ -w %{filename_effective} "${{ inputs.url }}")" com.DVloper.Granny3.apk config.arm64_v8a.apk
          ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: test
          files: |
            lib/arm64-v8a/libil2cpp.so
